### ISSUE TITLE
报错，为什么

### ISSUE THREAD

**Issue by gogoqiu** [dangnianchuntian/springboot#3]
Wrapper.java中
public class Wrapper<T> implements Serializable {

private Wrapper<T> message(String message) {
      this.setMessage(message);
this.setMessage, this.setResult等报错，没有这样的成员函数？

**Comment by dangnianchuntian** [comment]
项目用了lombok，检查一下idea是否安装lombok插件；类上有 @Data 标记；
idea安装lombok参考：
https://jingyan.baidu.com/article/0a52e3f4e53ca1bf63ed725c.html
