### ISSUE TITLE
Spring Boot实战分页查询附近的人: Redis+GeoHash+Lua的入参bug无法解决

### ISSUE THREAD

**Issue by paragonxza** [dangnianchuntian/springboot#5]
将代码原模原样clone下来运行的时候，用postman测试/list/nearby/people接口提醒如下error：
org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public java.lang.Object.com.zhanghan.zhnearbypeople.controller.GeoController.listNearByPeople(com.zhanghan.zhnearbypeople.controller.request.ListNearByPeopleRequest) with 3 errors: [Field error in object 'listNearByPeopleRequest' on field 'customerId': rejected value [null]; codes [NotNull.listNearByPeopleRequest.customerId,NotNull.customerId,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [listNearByPeopleRequest.customerId,customerId]; arguments []; default message [customerId]]; default message [不能为null]] [Field error in object 'listNearByPeopleRequest' on field 'pageIndex': rejected value [null];

**Comment by dangnianchuntian** [comment]
我刚测试一下是正常的；步骤如下： 
1.先加入测试测试数据
```json
http://127.0.0.1:8080/post/geo
{
    "customerId":"zhangsan",
    "longitude":39.996794,
    "latitude":116.48105
}
 
http://127.0.0.1:8080/post/geo
{
    "customerId":"sunliu",
    "longitude":39.787602,
    "latitude":116.562108 
}
```
2.调用查距离接口
```
http://127.0.0.1:8080/list/nearby/people
{
    "customerId":"sunliu",
    "pageIndex":1,
    "pageSize":10
}
```

**Comment by dangnianchuntian** [comment]
我刚测试一下是正常的；步骤如下： 
1.先加入测试测试数据
```json
http://127.0.0.1:8080/post/geo
{
    "customerId":"zhangsan",
    "longitude":39.996794,
    "latitude":116.48105
}
 
http://127.0.0.1:8080/post/geo
{
    "customerId":"sunliu",
    "longitude":39.787602,
    "latitude":116.562108 
}
```
2.调用查距离接口
```
http://127.0.0.1:8080/list/nearby/people
{
    "customerId":"sunliu",
    "pageIndex":1,
    "pageSize":10
}
```

**Comment by dangnianchuntian** [comment]
从你的报错来看是在调用/list/nearby/people接口时未传入customerId pageIndex pageSize 这三个参数
